import {
  Dashboard,
  Assignment,
  PrecisionManufacturing,
  Build,
  TaskAlt,
  Groups,
  Inventory2,
  ShoppingCart,
  Description,
  AccountBalanceWallet,
  Archive,
  BarChart,
  Timeline,
  Settings,
  Search,
  Person,
  Logout,
  Menu,
  ChevronRight,
  ExpandMore,
  ExpandLess,
  Delete,
  MoreVert,
  Warning,
  Edit,
  Visibility,
  Download,
  Print,
  Save,
  CropSquare,
  CheckBoxOutlineBlank,
  Fullscreen,
  ViewWeek,
  ViewAgenda,
  DragIndicator,
  Event,
  Check,
  CheckCircle,
  Straighten,
  AttachMoney,
  Schedule,
  Cancel,
  LocalShipping,
  CreditCard,
  Construction,
  Sync,
  Star,
  Store,
  Business,
  TrendingUp,
  Receipt,
  Assessment,
  HourglassTop,
  Error,
  Info,
  DriveEta,
  Lightbulb,
  AttachFile,
  Apartment,
  Help,
  Label,
  Folder,
  FolderOpen,
  FolderSpecial,
  UploadFile,
  MailOutline,
  Rule,
  Close,
  Phone,
  LocationOn,
  Add,
  AddCircleOutline,
  PlayArrow,
  TrackChanges,
  AccessTime,
  CameraAlt,
  Link,
  VpnKey,
  Lock,
  AdminPanelSettings,
  ContentCopy,
  Security,
  RocketLaunch,
  ReportProblem,
  History,
  SwapHoriz,
  PushPin,
  Remove,
  TrendingDown,
  CalendarMonth,
  ArrowForward,
  ArrowBack,
  // Bildirim sistemi icon'ları
  Notifications,
  NotificationsOff,
  NotificationsActive,
  DoneAll,
  Refresh,
  AssignmentInd,
  PersonAdd,
  Payments,
  Block,
  FitScreen,
  ZoomIn,
  ZoomOut,
  BrokenImage,
  PictureAsPdf,
  Image,
  // Yeni bildirim tipleri için eklenen ikonlar
  RequestQuote,
  Handshake,
  ThumbDown,
  Update,
  // Tedarikçi kategorileri ve config item'lar için
  Window,
  Layers,
  GridOn,
  Blinds,
  Curtains,
  FormatPaint,
  Home,
  Bolt,
  Category,
  HelpOutline,
  Palette,
} from '@mui/icons-material';

/** İkon adı -> MUI Icon bileşeni map */
export const NAV_ICONS = {
  dashboard: Dashboard,
  assignment: Assignment,
  factory: PrecisionManufacturing,
  build: Build,
  task_alt: TaskAlt,
  groups: Groups,
  inventory_2: Inventory2,
  shopping_cart: ShoppingCart,
  description: Description,
  account_balance_wallet: AccountBalanceWallet,
  archive: Archive,
  bar_chart: BarChart,
  monitoring: Timeline,
  settings: Settings,
};

export const UI_ICONS = {
  search: Search,
  person: Person,
  logout: Logout,
  menu: Menu,
  chevron_right: ChevronRight,
  expand_more: ExpandMore,
  expand_less: ExpandLess,
  delete: Delete,
  more_vert: MoreVert,
  warning: Warning,
  edit: Edit,
  visibility: Visibility,
  download: Download,
  print: Print,
  save: Save,
  crop_square: CropSquare,
  check_box_outline_blank: CheckBoxOutlineBlank,
  fullscreen: Fullscreen,
  view_week: ViewWeek,
  view_agenda: ViewAgenda,
  drag_indicator: DragIndicator,
  add: Add,
  settings: Settings,
  // Bildirim sistemi icon'ları
  notifications: Notifications,
  notifications_off: NotificationsOff,
  notifications_active: NotificationsActive,
  done_all: DoneAll,
  refresh: Refresh,
  sync: Sync,
  assignment_ind: AssignmentInd,
  check: Check,
  info: Info,
  error: Error,
  arrow_forward: ArrowForward,
  arrow_back: ArrowBack,
  person_add: PersonAdd,
  payments: Payments,
  block: Block,
  close: Close,
  // Lightbox icon'ları
  fit_screen: FitScreen,
  zoom_in: ZoomIn,
  zoom_out: ZoomOut,
  broken_image: BrokenImage,
  picture_as_pdf: PictureAsPdf,
  image: Image,
  // Diğer sık kullanılanlar
  check_circle: CheckCircle,
  cancel: Cancel,
  event: Event,
  local_shipping: LocalShipping,
  shopping_cart: ShoppingCart,
  assignment: Assignment,
  inventory: Inventory2,
  task_alt: TaskAlt,
  build: Build,
  upload_file: UploadFile,
  photo_camera: CameraAlt,
  camera: CameraAlt,
  draw: Edit,
  play_arrow: PlayArrow,
};

/** Durum / stat / rapor emoji → MUI icon map */
export const STATUS_ICONS = {
  '📅': Event,
  '✅': CheckCircle,
  '✓': CheckCircle,
  '📐': Straighten,
  '📄': Description,
  '💰': AttachMoney,
  '⏳': Schedule,
  '❌': Cancel,
  '📝': Assignment,
  '📦': Inventory2,
  '🔧': Build,
  '🚚': LocalShipping,
  '💳': CreditCard,
  '🛠️': Construction,
  '🔄': Sync,
  '📋': Assignment,
  '📊': BarChart,
  '👤': Person,
  '👥': Groups,
  '🏢': Business,
  '🏭': PrecisionManufacturing,
  '🛒': ShoppingCart,
  '⚠️': Warning,
  '⭐': Star,
  '💸': Receipt,
  '🏠': Store,
  '🪟': Build,
  '⏱️': HourglassTop,
  '🔴': Error,
  '🆕': Star,
  '🚫': Cancel,
  '❓': Help,
  '🚗': DriveEta,
  '💡': Lightbulb,
  '📎': AttachFile,
  '🏗️': Apartment,
  '🏷️': Label,
  '📏': Rule,
  '📁': Folder,
  '📂': FolderOpen,
  '🗂️': FolderSpecial,
  '📤': UploadFile,
  upload_file: UploadFile,
  '📭': MailOutline,
  '✕': Close,
  '🤝': Groups,
  '💵': AttachMoney,
  '📈': TrendingUp,
  '🕐': AccessTime,
  '✨': AddCircleOutline,
  '💾': Save,
  '▶️': PlayArrow,
  '🎯': TrackChanges,
  '📍': LocationOn,
  '📞': Phone,
  '↺': Sync,
  '🔗': Link,
  '📷': CameraAlt,
  '✍️': Edit,
  '➕': Add,
  '🔐': Lock,
  '🔑': VpnKey,
  '🚀': RocketLaunch,
  '🟢': CheckCircle,
  '🟡': Schedule,
  '⛔': Cancel,
  '🎉': Star,
  '⚙️': Settings,
  '⚡': Lightbulb,
  '🕒': AccessTime,
  '📜': History,
  '📆': CalendarMonth,
  // Material icon names (issue types, etc.)
  build: Build,
  help: Help,
  warning: Warning,
  inventory_2: Inventory2,
  assignment: Assignment,
  download: Download,
  close: Close,
  search: Search,
  '🔍': Search,
  comment: Description,
  '💬': Description,
  '⬇️': Download,
  '⬇': Download,
  straighten: Straighten,
  description: Description,
  folder_open: FolderOpen,
  phone: Phone,
  location_on: LocationOn,
  event: Event,
  attach_money: AttachMoney,
  attach_file: AttachFile,
  rule: Rule,
  precision_manufacturing: PrecisionManufacturing,
  folder: Folder,
  check_circle: CheckCircle,
  schedule: Schedule,
  cancel: Cancel,
  construction: Construction,
  credit_card: CreditCard,
  local_shipping: LocalShipping,
  add_circle_outline: AddCircleOutline,
  history: History,
  bar_chart: BarChart,
  rocket_launch: RocketLaunch,
  // Yeni bildirim tipleri ikonları
  request_quote: RequestQuote,
  handshake: Handshake,
  thumb_down: ThumbDown,
  update: Update,
  // Tedarikçi kategorileri ve config item'lar için
  window: Window,
  layers: Layers,
  grid_on: GridOn,
  blinds: Blinds,
  curtains: Curtains,
  format_paint: FormatPaint,
  bolt: Bolt,
  category: Category,
  help_outline: HelpOutline,
  palette: Palette,
};

/** Arşiv / belge ikon adı -> MUI Icon */
export const ARCHIVE_ICONS = {
  straighten: Straighten,
  rule: Rule,
  assignment: Assignment,
  attach_money: AttachMoney,
  apartment: Apartment,
  home: Home,
  inventory_2: Inventory2,
  build: Build,
  check_circle: CheckCircle,
  drive_eta: DriveEta,
  precision_manufacturing: PrecisionManufacturing,
  store: Store,
  folder: Folder,
  receipt: Receipt,
  description: Description,
  folder_open: FolderOpen,
  folder_special: FolderSpecial,
  bar_chart: BarChart,
  work: Assignment,
  business: Business,
  groups: Groups,
  upload_file: UploadFile,
  close: Close,
  mail_outline: MailOutline,
  lock: Lock,
  logout: Logout,
  sync: Sync,
  person: Person,
  event: Event,
  cancel: Cancel,
  local_shipping: LocalShipping,
  star: Star,
  label: Label,
  vpn_key: VpnKey,
  admin_panel_settings: AdminPanelSettings,
  content_copy: ContentCopy,
  security: Security,
  shopping_cart: ShoppingCart,
  camera_alt: CameraAlt,
  swap_horiz: SwapHoriz,
  push_pin: PushPin,
  remove: Remove,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  credit_card: CreditCard,
};

/** StatusIcon: emoji veya icon adı ile MUI ikon render */
export const StatusIcon = ({ icon, ...props }) => {
  const Icon = typeof icon === 'string' ? STATUS_ICONS[icon] || UI_ICONS[icon] : icon;
  if (!Icon) return null;
  return <Icon {...props} fontSize="small" aria-hidden />;
};

/**
 * @param {string} name - İkon adı (snake_case)
 * @param {object} props - MUI SvgIcon props (fontSize, sx, className vb.)
 */
export const NavIcon = ({ name, ...props }) => {
  const Icon = NAV_ICONS[name];
  if (!Icon) return null;
  return <Icon {...props} fontSize="small" aria-hidden />;
};

/**
 * @param {string} name - İkon adı (snake_case)
 * @param {object} props - MUI SvgIcon props
 */
export const UIIcon = ({ name, ...props }) => {
  const Icon = UI_ICONS[name];
  if (!Icon) return null;
  return <Icon {...props} fontSize="small" aria-hidden />;
};

/** ArchiveIcon: icon adı veya emoji (legacy) ile MUI ikon render */
export const ArchiveIcon = ({ icon, ...props }) => {
  const Icon = typeof icon === 'string'
    ? ARCHIVE_ICONS[icon] || STATUS_ICONS[icon] || UI_ICONS[icon]
    : icon;
  if (!Icon) return null;
  return <Icon {...props} fontSize="small" aria-hidden />;
};
